// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const ACTIVE_SUPABASE_URL = 'https://pyldmmsqezsqrgfcidue.supabase.co';
const ACTIVE_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_FTbGT_xnBwBLf9abTM_n4A_SHi0sNFu';
const LEGACY_SUPABASE_URL = 'https://zoeuyehnuhmmgxusdfox.supabase.co';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Force the active project values if stale deployment env still points to the old project.
const SUPABASE_URL = envSupabaseUrl === LEGACY_SUPABASE_URL ? ACTIVE_SUPABASE_URL : (envSupabaseUrl || ACTIVE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = envSupabasePublishableKey || ACTIVE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});